# 指定构建环境
language: node_js
node_js: --lts

# 设置缓存文件
cache:
  directories:
    - node_modules

# 在构建之前安装环境、替换GH_TOKEN
before_script:
  - npm install -g hexo-cli
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml

# 安装依赖
install:
  - npm install

# 执行清缓存
script:
  - hexo g
  - hexo d